# Generated by Django 2.0.5 on 2018-05-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180504_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilities', models.FileField(upload_to='')),
                ('humanCapital', models.FileField(upload_to='')),
                ('assets', models.FileField(upload_to='')),
            ],
        ),
    ]
