# Generated by Django 2.0.5 on 2018-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itoperation',
            name='assets',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='itoperation',
            name='humanCapital',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='itoperation',
            name='utilities',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
