# Generated by Django 2.0.5 on 2018-05-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180506_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itoperation',
            options={'permissions': (('uep', 'Permiso de test'),)},
        ),
    ]
