# Generated by Django 2.0.5 on 2018-05-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180530_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itoperation',
            options={'permissions': (('see_itoperation', 'Ver la capa de operación'),)},
        ),
    ]
