# Generated by Django 2.0.5 on 2018-05-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_itmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmanagement',
            name='services',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
