# Generated by Django 2.0.5 on 2018-05-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180530_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmanagement',
            name='services',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
