# Generated by Django 2.0.5 on 2018-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180530_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITGovernance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('evaluation', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('monitorization', models.FileField(blank=True, upload_to='documents/%Y/%m/%d')),
            ],
            options={
                'permissions': (('see_itgovernance', 'Ver la capa de governanza'),),
            },
        ),
    ]
