# Generated by Django 2.0.5 on 2018-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_itgovernance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpGovernance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structures', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('applications', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('value', models.FileField(blank=True, upload_to='documents/%Y/%m/%d')),
            ],
            options={
                'permissions': (('see_corpgovernance', 'Ver la capa de el gobierno corporativo'),),
            },
        ),
    ]
