# Generated by Django 2.0.5 on 2018-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_corpgovernance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpgovernance',
            old_name='structures',
            new_name='structuresFile',
        ),
        migrations.AddField(
            model_name='corpgovernance',
            name='structuresName',
            field=models.CharField(default='Estructuras', max_length=100),
            preserve_default=False,
        ),
    ]
