# Generated by Django 2.0.5 on 2018-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180602_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpgovernance',
            old_name='applications',
            new_name='applicationsFile',
        ),
        migrations.RenameField(
            model_name='corpgovernance',
            old_name='value',
            new_name='valueFile',
        ),
        migrations.RenameField(
            model_name='itgovernance',
            old_name='direction',
            new_name='directionFile',
        ),
        migrations.RenameField(
            model_name='itgovernance',
            old_name='evaluation',
            new_name='evaluationFile',
        ),
        migrations.RenameField(
            model_name='itgovernance',
            old_name='monitorization',
            new_name='monitorizationFile',
        ),
        migrations.RenameField(
            model_name='itmanagement',
            old_name='businessProcesses',
            new_name='businessProcessesFile',
        ),
        migrations.RenameField(
            model_name='itmanagement',
            old_name='projects',
            new_name='projectsFile',
        ),
        migrations.RenameField(
            model_name='itoperation',
            old_name='assets',
            new_name='assetsFile',
        ),
        migrations.RenameField(
            model_name='itoperation',
            old_name='humanCapital',
            new_name='humanCapitalFile',
        ),
        migrations.RenameField(
            model_name='itoperation',
            old_name='utilities',
            new_name='utilitiesFile',
        ),
        migrations.RemoveField(
            model_name='itmanagement',
            name='services',
        ),
        migrations.AddField(
            model_name='corpgovernance',
            name='applicationsName',
            field=models.CharField(default='Aplicaciones', max_length=100),
        ),
        migrations.AddField(
            model_name='corpgovernance',
            name='valueName',
            field=models.CharField(default='Valor', max_length=100),
        ),
        migrations.AddField(
            model_name='itgovernance',
            name='directionName',
            field=models.CharField(default='Dirección', max_length=100),
        ),
        migrations.AddField(
            model_name='itgovernance',
            name='evaluationName',
            field=models.CharField(default='Evaluación', max_length=100),
        ),
        migrations.AddField(
            model_name='itgovernance',
            name='monitorizationName',
            field=models.CharField(default='Monitorización', max_length=100),
        ),
        migrations.AddField(
            model_name='itmanagement',
            name='businessProcessesName',
            field=models.CharField(default='Procesos de negocio', max_length=100),
        ),
        migrations.AddField(
            model_name='itmanagement',
            name='projectsName',
            field=models.CharField(default='Proyectos', max_length=100),
        ),
        migrations.AddField(
            model_name='itmanagement',
            name='servicesFile',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='itmanagement',
            name='servicesName',
            field=models.CharField(default='Servicios', max_length=100),
        ),
        migrations.AddField(
            model_name='itoperation',
            name='assetsName',
            field=models.CharField(default='Activos', max_length=100),
        ),
        migrations.AddField(
            model_name='itoperation',
            name='humanCapitalName',
            field=models.CharField(default='Personal', max_length=100),
        ),
        migrations.AddField(
            model_name='itoperation',
            name='utilitiesName',
            field=models.CharField(default='Utilidades', max_length=100),
        ),
    ]
