# Generated by Django 2.0.5 on 2018-06-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180602_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itoperation',
            name='utilitiesName',
            field=models.CharField(default='Utilidades', max_length=100, verbose_name='utilities'),
        ),
    ]
