# Generated by Django 2.0.5 on 2018-06-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180602_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='itoperation',
            name='arrow1File',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='itoperation',
            name='arrow1Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itoperation',
            name='arrow2File',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='itoperation',
            name='arrow2Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itoperation',
            name='utilitiesName',
            field=models.CharField(default='Utilidades', max_length=100),
        ),
    ]
